### ISSUE TITLE
Cannot find `python3` or `python2` binary

### ISSUE THREAD

**Issue by radarhere** [tidelift/alignment-action#2]
Hi. Over at https://github.com/python-pillow/Pillow, we have been using [your action successfully](https://github.com/python-pillow/Pillow/runs/5087523242), until the Tidelift CLI version went from 1.5.3-build-4480 to 1.5.7-build-4542.

It then started reporting ["Error: found a `requirements.txt` file, but cannot find `python3` or `python2` binary."](https://github.com/python-pillow/Pillow/runs/5117104138)

I attempted to setup Python in an earlier part of the GitHub actions run, but to no avail. I now suspect the problem is that the Docker in this repository doesn't have Python.

Do you think I am correct, and that this repository needs to install Python? If you think the problem resides elsewhere, please let me know - I can't find anywhere to report a bug with the Tidelift CLI, aside from just e-mailing Tidelift.

**Comment by tiegz** [comment]
Hey @radarhere 👋🏻 thanks for the detailed bug report.

We just released a bugfix in 1.5.4 that was silencing some errors like this instead of exiting the command. I think that your error was being silenced in the past, which prevented the CLI from trying to generate a full dependency list. 

If you want to fix it by installing python on that workflow's image, the CLI would then do its own pip freeze to get a full list of deps. 

Otherwise, you can set `TIDELIFT_PYTHON_NO_RESOLVE=1` in the action to skip the pip freeze, and it will align against the files it was using before: Pipfile, Pipfile.lock, requirements.txt, and setup.py.

**Comment by radarhere** [comment]
Ah, ok, interesting. Thanks for your quick response.

Here is what I've tried to do to install Python. I'm able to execute `python3` successfully afterwards, but I still get [the same error](https://github.com/python-pillow/Pillow/runs/5117362058). I don't suppose you have any ideas?

```
name: Tidelift Align
on:
  push:
    paths:
      - ".github/workflows/tidelift.yml"
  pull_request:
    paths:
      - ".github/workflows/tidelift.yml"
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'python-pillow'
    name: Run Tidelift to ensure approved open source packages are in use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Test Python
        run: |
          python3 --version
      - name: Scan
        uses: tidelift/alignment-action@main
        env:
          TIDELIFT_API_KEY: ${{ secrets.TIDELIFT_API_KEY }}
          TIDELIFT_ORGANIZATION: team/aclark4life
          TIDELIFT_PROJECT: pillow
```

**Comment by tiegz** [comment]
That is strange! 🧐  I will take a look at this first thing in the morning @radarhere

**Comment by tiegz** [comment]
@radarhere if you rerun the Tidelift action, it should now run without trying lockfile resolution (since it won't work anyway) and should fix the build. We've added a note on the action's README that lockfiles should already exist too to clarify.

**Comment by radarhere** [comment]
Yes, it is fixed now. Thanks very much
